import { TutorialStep } from "@/contexts/TutorialContext"

export const setupTutorialSteps: TutorialStep[] = [
  {
    id: "welcome",
    title: "Welcome to Budget Buddy",
    description: "Let's get you set up! We'll guide you through all the features to help you master your finances.",
    target: "dashboard",
    position: "bottom",
    route: "/",
  },
  {
    id: "dashboard-overview",
    title: "Your Dashboard",
    description: "This is your financial command center. View your balance, recent transactions, and top spending categories at a glance.",
    target: "dashboard-summary",
    position: "bottom",
    route: "/",
  },
  {
    id: "categories",
    title: "Organize with Categories",
    description: "Categories help organize your transactions. Create categories like 'Groceries', 'Transport', or 'Entertainment' to track where your money goes.",
    target: "categories-page",
    position: "bottom",
    route: "/categories",
  },
  {
    id: "budgets",
    title: "Set Spending Limits",
    description: "Budgets help you track spending limits for different categories. Set monthly, weekly, or yearly budgets to stay on track.",
    target: "budgets-page",
    position: "bottom",
    route: "/budgets",
  },
  {
    id: "transactions",
    title: "Track Your Spending",
    description: "Add and manage all your income and expenses here. You can filter, search, and categorize transactions.",
    target: "transactions-page",
    position: "bottom",
    route: "/transactions",
  },
  {
    id: "quick-add",
    title: "Quick Add Transaction",
    description: "Use this button to quickly add transactions without leaving the current page. Perfect for on-the-go tracking.",
    target: "quick-add-button",
    position: "top",
    route: "/transactions",
  },
  {
    id: "savings-intro",
    title: "Build Your Savings",
    description: "Create savings pots for specific goals like vacations, emergencies, or big purchases. Set targets and track your progress.",
    target: "savings-page",
    position: "bottom",
    route: "/savings",
  },
  {
    id: "savings-pots",
    title: "Create Savings Pots",
    description: "Click here to create a new savings pot. Give it a name, set a target amount, and choose how much to contribute regularly.",
    target: "savings-pots",
    position: "bottom",
    route: "/savings",
  },
  {
    id: "savings-allocations",
    title: "Allocate Money to Pots",
    description: "Move money from your main balance to your savings pots. Track all your allocations and withdrawals here.",
    target: "savings-allocations",
    position: "bottom",
    route: "/savings",
  },
  {
    id: "savings-forecast",
    title: "See Your Future",
    description: "View projections of when you'll reach your savings goals based on your current contribution rate.",
    target: "savings-forecast",
    position: "bottom",
    route: "/savings",
  },
  {
    id: "analytics-intro",
    title: "Understand Your Spending",
    description: "Analytics provide insights into your financial patterns. View spending trends, category breakdowns, and your financial health score.",
    target: "analytics-page",
    position: "bottom",
    route: "/analytics",
  },
  {
    id: "analytics-trends",
    title: "Spending Trends",
    description: "Visualize your income, expenses, and savings over time. Identify patterns and make informed decisions.",
    target: "analytics-trends",
    position: "bottom",
    route: "/analytics",
  },
  {
    id: "analytics-categories",
    title: "Category Breakdown",
    description: "See which categories consume most of your budget. Use this to identify areas where you can cut back.",
    target: "analytics-breakdown",
    position: "bottom",
    route: "/analytics",
  },
  {
    id: "analytics-health",
    title: "Financial Health Score",
    description: "Get an overall score of your financial health based on savings rate, budget adherence, and income stability.",
    target: "analytics-health",
    position: "bottom",
    route: "/analytics",
  },
  {
    id: "alerts-intro",
    title: "Stay Informed",
    description: "Alerts notify you about important financial events like budget overspending, low balances, or unusual spending patterns.",
    target: "alerts-page",
    position: "bottom",
    route: "/alerts",
  },
  {
    id: "alerts-preferences",
    title: "Customize Alerts",
    description: "Choose which types of alerts you want to receive and set thresholds. Only get notified about what matters to you.",
    target: "alerts-preferences",
    position: "bottom",
    route: "/alerts",
  },
  {
    id: "partners-intro",
    title: "Share with Partners",
    description: "Invite a partner to share financial insights. Great for couples who want to manage finances together.",
    target: "partners-page",
    position: "bottom",
    route: "/partners",
  },
  {
    id: "dashboard-widgets",
    title: "Customize Your Dashboard",
    description: "Add, remove, and rearrange widgets to create a dashboard that shows exactly what you need.",
    target: "custom-dashboard",
    position: "bottom",
    route: "/dashboard/custom",
  },
  {
    id: "profile-settings",
    title: "Manage Your Profile",
    description: "Update your account details, change your currency, timezone, and other personal preferences.",
    target: "profile-page",
    position: "bottom",
    route: "/profile",
  },
  {
    id: "complete",
    title: "You're All Set!",
    description: "Congratulations! You've learned all the features of Budget Buddy. Start tracking your finances and achieve your financial goals!",
    target: "dashboard",
    position: "bottom",
    route: "/",
  },
]
