import { TutorialStep } from "@/contexts/TutorialContext"

export const setupTutorialSteps: TutorialStep[] = [
  {
    id: "welcome",
    title: "Welcome to Bêre Bietjie!",
    description: "Let's set up your budget together. We'll guide you through the setup in the correct order so you understand how everything works. Ready to get started?",
    target: "dashboard",
    position: "bottom",
    route: "/",
  },
  {
    id: "categories-step-1",
    title: "Step 1: Create Categories",
    description: "First, we need to create categories. Categories are the foundation of your budget - they organize where your money goes. Think of categories like 'Groceries', 'Rent', 'Transport', etc. You'll need these before setting budgets or adding transactions.",
    target: "categories-page",
    position: "bottom",
    route: "/categories",
  },
  {
    id: "categories-step-2",
    title: "Add Your First Category",
    description: "Click the 'Add Category' button to create your first category. Start with essentials like 'Groceries' or 'Rent'. You can always add more later.",
    target: "add-category-button",
    position: "bottom",
    route: "/categories",
  },
  {
    id: "categories-step-3",
    title: "Create a Few More Categories",
    description: "Add 3-5 more categories to cover your main spending areas. Common ones: Transport, Entertainment, Utilities, Shopping. Don't worry about being perfect - you can adjust anytime.",
    target: "categories-list",
    position: "bottom",
    route: "/categories",
  },
  {
    id: "budgets-step-1",
    title: "Step 2: Set Up Budgets",
    description: "Now that you have categories, let's set budget limits. Budgets help you track how much you want to spend in each category. This is how you control your spending.",
    target: "budgets-page",
    position: "bottom",
    route: "/budgets",
  },
  {
    id: "budgets-step-2",
    title: "Create Your First Budget",
    description: "Click 'Add Budget' and select one of your categories. Set a monthly limit based on what you typically spend. For example, if you usually spend R2000 on groceries, set your grocery budget to R2000.",
    target: "add-budget-button",
    position: "bottom",
    route: "/budgets",
  },
  {
    id: "budgets-step-3",
    title: "Set Up More Budgets",
    description: "Create budgets for your other main categories. Start with the ones you know best. You can always adjust amounts later as you track your actual spending.",
    target: "budgets-list",
    position: "bottom",
    route: "/budgets",
  },
  {
    id: "transactions-step-1",
    title: "Step 3: Add Your First Transaction",
    description: "Now let's add some transactions. Transactions are your actual income and expenses. This is how you track what's really happening with your money.",
    target: "transactions-page",
    position: "bottom",
    route: "/transactions",
  },
  {
    id: "transactions-step-2",
    title: "Record an Expense",
    description: "Click 'Add Transaction' to record a recent purchase. Select the category you created, enter the amount, and add a description. This starts building your spending history.",
    target: "add-transaction-button",
    position: "bottom",
    route: "/transactions",
  },
  {
    id: "transactions-step-3",
    title: "Add a Few More Transactions",
    description: "Add 3-5 more transactions to different categories. Include both expenses (money going out) and income (money coming in). This gives you a realistic picture of your finances.",
    target: "transactions-list",
    position: "bottom",
    route: "/transactions",
  },
  {
    id: "savings-step-1",
    title: "Step 4: Set Up Savings Goals",
    description: "Now let's create savings pots for your goals. Savings pots help you set aside money for specific purposes like emergencies, vacations, or big purchases.",
    target: "savings-page",
    position: "bottom",
    route: "/savings",
  },
  {
    id: "savings-step-2",
    title: "Create Your First Savings Pot",
    description: "Click 'Add Pot' and give it a name like 'Emergency Fund' or 'Vacation'. Set a target amount and how much you want to contribute regularly. This makes saving automatic and intentional.",
    target: "add-pot-button",
    position: "bottom",
    route: "/savings",
  },
  {
    id: "dashboard-step-1",
    title: "Step 5: Customize Your Dashboard",
    description: "Your dashboard shows you what's happening with your money. You can customize which widgets to display and how they're arranged.",
    target: "dashboard",
    position: "bottom",
    route: "/",
  },
  {
    id: "dashboard-step-2",
    title: "Customize Your View",
    description: "Click 'Customize' to add, remove, or rearrange widgets. Show what matters most to you - recent transactions, spending trends, savings progress, or budget status.",
    target: "customize-button",
    position: "bottom",
    route: "/",
  },
  {
    id: "complete",
    title: "You're All Set!",
    description: "Congratulations! You've set up the foundation of your budget. Now you can: add transactions regularly, monitor your budgets, track savings progress, and use analytics to understand your spending patterns. Your dashboard will update automatically as you add data.",
    target: "dashboard",
    position: "bottom",
    route: "/",
  },
]
