import { TutorialStep } from "@/contexts/TutorialContext"

export const setupTutorialSteps: TutorialStep[] = [
  {
    id: "welcome",
    title: "Welcome to Bêre Bietjie!",
    description: "Great news - we've already created some default categories and budgets to help you get started! Let's walk through the app features so you can make the most of your budget. Ready to explore?",
    target: "dashboard",
    position: "bottom",
    route: "/",
  },
  {
    id: "categories-step-1",
    title: "Step 1: Your Categories",
    description: "Categories organize where your money goes. We've created common ones like Groceries, Rent, Utilities, Transport, and Entertainment. You can edit these or add new ones anytime to match your lifestyle.",
    target: "categories-page",
    position: "bottom",
    route: "/categories",
  },
  {
    id: "categories-step-2",
    title: "Customize Your Categories",
    description: "Click on any category to edit its name, icon, or color. Add new categories for things specific to you - like 'Pet expenses' or 'Hobbies'. The more specific your categories, the better you can track your spending.",
    target: "categories-list",
    position: "bottom",
    route: "/categories",
  },
  {
    id: "budgets-step-1",
    title: "Step 2: Your Budgets",
    description: "Budgets help you control spending by setting limits for each category. We've created starter budgets for Groceries, Rent, Utilities, Transport, and Entertainment. Adjust these amounts based on what you actually spend.",
    target: "budgets-page",
    position: "bottom",
    route: "/budgets",
  },
  {
    id: "budgets-step-2",
    title: "Adjust Your Budgets",
    description: "Click on any budget to change the amount or period. You can also click on a budget card to see all transactions in that category. This helps you understand where your money is going.",
    target: "budgets-list",
    position: "bottom",
    route: "/budgets",
  },
  {
    id: "transactions-step-1",
    title: "Step 3: Track Transactions",
    description: "Transactions are your actual income and expenses. Adding them regularly is key to understanding your finances. You can add them here or use the quick add on the dashboard.",
    target: "transactions-page",
    position: "bottom",
    route: "/transactions",
  },
  {
    id: "transactions-step-2",
    title: "Add Your Transactions",
    description: "Click 'Add Transaction' to record purchases or income. Select a category, enter the amount, and add a description. The more you track, the clearer your financial picture becomes.",
    target: "add-transaction-button",
    position: "bottom",
    route: "/transactions",
  },
  {
    id: "savings-step-1",
    title: "Step 4: Savings Goals",
    description: "Create savings pots for specific goals like emergencies, vacations, or big purchases. Set a target amount and contribute regularly. Watch your savings grow over time!",
    target: "savings-page",
    position: "bottom",
    route: "/savings",
  },
  {
    id: "savings-step-2",
    title: "Create Savings Pots",
    description: "Click 'Add Pot' to create a new savings goal. You can allocate money from your balance to different pots and track your progress toward each goal.",
    target: "add-pot-button",
    position: "bottom",
    route: "/savings",
  },
  {
    id: "credits-step-1",
    title: "Step 5: Track Credits",
    description: "If you have credit cards, loans, or other debt, use the Credits feature to track your payoff progress. Set up monthly payment plans and see forecasts for when you'll be debt-free.",
    target: "credits-page",
    position: "bottom",
    route: "/credits",
  },
  {
    id: "credits-step-2",
    title: "Add Your Credits",
    description: "Click 'Add Credit' to track a credit card, loan, or other debt. Set the total amount, monthly payment, and interest rate. We'll show you your payoff timeline.",
    target: "add-credit-button",
    position: "bottom",
    route: "/credits",
  },
  {
    id: "analytics-step-1",
    title: "Step 6: Understand Your Spending",
    description: "Analytics shows you patterns in your spending. View trends over time, see category breakdowns, and check your financial health score. This helps you make smarter money decisions.",
    target: "analytics-page",
    position: "bottom",
    route: "/analytics",
  },
  {
    id: "dashboard-step-1",
    title: "Step 7: Your Dashboard",
    description: "Your dashboard gives you a quick overview of everything. Customize it to show what matters most to you - recent transactions, budget progress, savings goals, spending trends, and more.",
    target: "dashboard",
    position: "bottom",
    route: "/",
  },
  {
    id: "dashboard-step-2",
    title: "Customize Your View",
    description: "Click 'Customize' to add, remove, or rearrange widgets. Drag them to organize your dashboard exactly how you like it.",
    target: "customize-button",
    position: "bottom",
    route: "/",
  },
  {
    id: "alerts-step-1",
    title: "Step 8: Set Up Alerts",
    description: "Get notified when you're approaching budget limits or when important events happen. Set up alerts to stay on top of your finances without constantly checking the app.",
    target: "alerts-page",
    position: "bottom",
    route: "/alerts",
  },
  {
    id: "complete",
    title: "You're All Set!",
    description: "Congratulations! You now know all the features. Regularly add transactions, monitor your budgets, track savings progress, manage credits, and check analytics to understand your spending patterns. Your dashboard updates automatically as you use the app.",
    target: "dashboard",
    position: "bottom",
    route: "/",
  },
]
